# FONT
font_family family='JetBrains Mono'
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11.25

# THEME
include themes/mocha.conf
background_opacity 0.75

# PADDING
window_padding_width 10

# BELL
enable_audio_bell no
