$font = Montserrat

general {
	hide_cursor = true
}

auth {
	fingerprint {
		enabled = true
		ready_message = Scan fingerprint to unlock
		present_message = Scanning
		retry_delay = 250
	}
}

animations {
	enabled = false
}

background {
	monitor =
	path = 
	color = rgb(282828)
}

input-field {
	monitor = 
	size = 30%, 5%
	
	swap_font_color = true
	outline_thickness = 1
	inner_color = rgb(3c3836)
	outer_color = rgb(3c3836)
	check_color = rgb(d79921)
	fail_color = rgb(cc241d)

	font_family = $font
	font_color = rgb(ebdbb2)
	dots_spacing = 0.3
	dots_size = 0.2
	placeholder_text = <span color="##a89984">Password</span>
	fail_text = $PAMFAIL
	
	fade_on_empty = false
	rounding = -1

	position = 0, -5%
	halign = center
	valign = center
}

label {
	monitor =

	text = <b>$TIME</b>
	font_size = 50
	font_family = $font
	color = rgb(ebdbb2)

	position = 0, 10%
	halign = center
	valign = center
}

label {
	monitor =

	text = cmd[update:60000] date +"%A, %d %B %Y"
	font_size = 14
	font_family = $font
	color = rgb(a89984)

	position = 0, 5%
	halign = center
	valign = center
}

label {
	monitor =

	text = $FPRINTPROMPT
	font_family = $font
	font_size = 18
	color = rgb(d5c4a1)

	position = 0, -10%
	halign = center
	valign = center
}
